create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.organization_members (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'staff' check (role in ('admin', 'scheduler', 'staff', 'viewer')),
  created_at timestamptz not null default timezone('utc', now()),
  unique (organization_id, user_id)
);

create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  organization_id uuid references public.organizations(id) on delete cascade,
  shift_date date not null,
  shift_name text not null check (shift_name in ('morning', 'afternoon', 'night')),
  assigned_to text not null default '',
  notes text,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.schedules
  add column if not exists organization_id uuid references public.organizations(id) on delete cascade;

do $$
declare default_org_id uuid;
begin
  select id into default_org_id
  from public.organizations
  where name = 'Default Hospital'
  limit 1;

  if default_org_id is null then
    insert into public.organizations (name)
    values ('Default Hospital')
    returning id into default_org_id;
  end if;

  update public.schedules
  set organization_id = default_org_id
  where organization_id is null;
end $$;

alter table public.schedules
  alter column organization_id set not null;

alter table public.schedules
  drop constraint if exists schedules_shift_date_shift_name_key;

drop index if exists schedules_shift_date_shift_name_key;
create unique index if not exists schedules_org_date_shift_unique
  on public.schedules (organization_id, shift_date, shift_name);

create index if not exists schedules_organization_id_idx
  on public.schedules (organization_id);

create index if not exists organization_members_user_id_idx
  on public.organization_members (user_id);

alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.schedules enable row level security;

drop policy if exists "Organization members can read organizations" on public.organizations;
create policy "Organization members can read organizations"
on public.organizations
for select
to authenticated
using (
  exists (
    select 1
    from public.organization_members om
    where om.organization_id = organizations.id
      and om.user_id = auth.uid()
  )
);

drop policy if exists "Users can read own memberships" on public.organization_members;
create policy "Users can read own memberships"
on public.organization_members
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Organization members can read schedules" on public.schedules;
create policy "Organization members can read schedules"
on public.schedules
for select
to authenticated
using (
  exists (
    select 1
    from public.organization_members om
    where om.organization_id = schedules.organization_id
      and om.user_id = auth.uid()
  )
);

drop policy if exists "Schedulers and admins can insert schedules" on public.schedules;
create policy "Schedulers and admins can insert schedules"
on public.schedules
for insert
to authenticated
with check (
  exists (
    select 1
    from public.organization_members om
    where om.organization_id = schedules.organization_id
      and om.user_id = auth.uid()
      and om.role in ('admin', 'scheduler')
  )
);

drop policy if exists "Schedulers and admins can update schedules" on public.schedules;
create policy "Schedulers and admins can update schedules"
on public.schedules
for update
to authenticated
using (
  exists (
    select 1
    from public.organization_members om
    where om.organization_id = schedules.organization_id
      and om.user_id = auth.uid()
      and om.role in ('admin', 'scheduler')
  )
)
with check (
  exists (
    select 1
    from public.organization_members om
    where om.organization_id = schedules.organization_id
      and om.user_id = auth.uid()
      and om.role in ('admin', 'scheduler')
  )
);
