create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  shift_date date not null,
  shift_name text not null check (shift_name in ('morning', 'afternoon', 'night')),
  assigned_to text not null default '',
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  unique (shift_date, shift_name)
);

alter table public.schedules enable row level security;

drop policy if exists "Public read schedules" on public.schedules;
create policy "Public read schedules"
on public.schedules
for select
to anon, authenticated
using (true);

drop policy if exists "Public write schedules" on public.schedules;
create policy "Authenticated write schedules"
on public.schedules
for insert
to authenticated
with check (true);

drop policy if exists "Public update schedules" on public.schedules;
create policy "Authenticated update schedules"
on public.schedules
for update
to authenticated
using (true)
with check (true);
